### ISSUE TITLE
Create fails due to "AnsibleConfigServer"

### ISSUE THREAD

**Issue by dudash** [aws-quickstart/quickstart-redhat-openshift#90]
I'm getting this error every time I try to roll this out.  It seems to create all the EC2s, security groups, ansible bastion, etc.  I tried turning off automatic rollbacks and digging around on the ansible EC2 - but didn't see anything obviously wrong.  Going into a master node if I try to 'oc get pods' there are none.

I've tried this in us-east Ohio and in N.VA.  I've tried with the default "Subscription-Version" of "3.7.23-1" and I've tried with the "Opensource-Version" or "3.9.8-1". 

Any tips on debugging further or a fix?

```Embedded stack arn:aws:cloudformation:us-east-2:150898592263:stack/Red-Hat-OpenShift-OpenShiftStack-3N79BVI1Y33O/80814a30-2858-11e8-9e22-50a686f309d1 was not successfully created: The following resource(s) failed to create: [AnsibleConfigServer].```

Here are the paramters from my last try:
```
AnsiblePlaybookGitRepoTag | 3.7.23-1 |  
-- | -- | --
AnsiblePlaybookType | Subscription-Version |  
AvailabilityZones | us-east-2a,us-east-2b,us-east-2c |  
ContainerAccessCIDR | 0.0.0.0/0 |  
EtcdInstanceType | m4.xlarge |  
KeyPairName | openshiftistio-ohio |  
MasterInstanceType | m4.xlarge |  
NodesInstanceType | m4.xlarge |  
NumberOfEtcd | 3 |  
NumberOfMaster | 3 |  
NumberOfNodes | 3 |  
OpenShiftAdminPassword | **** |  
OutputBucketName |   |  
PrivateSubnet1CIDR | 10.0.0.0/19 |  
PrivateSubnet2CIDR | 10.0.32.0/19 |  
PrivateSubnet3CIDR | 10.0.64.0/19 |  
PublicSubnet1CIDR | 10.0.128.0/20 |  
PublicSubnet2CIDR | 10.0.144.0/20 |  
PublicSubnet3CIDR | 10.0.160.0/20 |  
QSS3BucketName | quickstart-reference |  
QSS3KeyPrefix | redhat/openshift/latest/ |  
RedhatSubscriptionPassword | REMOVED |  
RedhatSubscriptionPoolID | REMOVED |  
RedhatSubscriptionUserName | REMOVED |  
RemoteAccessCIDR | 0.0.0.0/0 |  
VPCCIDR | 10.0.0.0/16
```

**Comment by jaymccon** [comment]
Hi @dudash,

The relevant logs will be on the bastion host, which is used to configure the cluster with ansible, from cloud-init (`journalct | grep cloud-init`) and ansible (`cat /var/log/ansible.log`).

feel free to post some of the logs here, but be sure to check them for secrets and redact them first.

**Comment by philipho11** [comment]
I am rolling out version 1.3 (because want to have the DNS 53 integration) but got error. Attached the logs (journalct | grep cloud-init) 

[logs.txt](https://github.com/aws-quickstart/quickstart-redhat-openshift/files/1825536/logs.txt)

**Comment by jaymccon** [comment]
Hi,

from the logs it looks like the aws service broker deployment script is failing to get the CA cert:

```
Mar 19 14:51:29 ip-10-0-135-0.ap-southeast-2.compute.internal cloud-init[1664]: Unable to set the BROKER_CA_CERT variable!
```

If possible can you please ssh into the 1st master node that is listed in `/etc/ansible/hosts` (file if located on the bastion/configserver). Once in try and manually run the failing command and see if the output makes the cause any more clear.

```bash
oc get secret -n kube-service-catalog -o go-template='{{ range .items }}{{ if eq .type "kubernetes.io/service-account-token" }}{{ index .data "service-ca.crt" }}{{end}}{{"\n"}}{{end}}' | awk NF | tail -n 1
```

The script expects the output of the above to be a CA cert.

**Comment by philipho11** [comment]
I just turned off AWS service broker and everything seems fine now. If you want the previous error, I can re-build the stack and show you.

**Comment by philipho11** [comment]
NoVolumeZoneConflict seems to occur for all involving persistent storage. I am using Version 1.3. Attached is a launch of Mongodb persistent instance. Mondodb Ephemeral works okay.

![firefox_screenshot_2018-03-21t04-01-58 882z](https://user-images.githubusercontent.com/10525442/37694164-eb2c2cbe-2cff-11e8-81fc-75c9ed75b7e8.png)

I also tried to create a separate storage in GUI. The EBS can launch okay. But when I delete the storage in GUI, the oc get pv shows fail status. Attached is the log too. Something wrong with persistent storage?

![screenshot from 2018-03-21 12-06-51](https://user-images.githubusercontent.com/10525442/37694223-67b4ca70-2d00-11e8-94eb-ac26a0ad2b14.png)

**Comment by jaymccon** [comment]
@philipho11 just in case the EBS issue is unrelated I've created a new issue for your most recent comment.

I will attempt to replicate the issue, in the meantime you may want to try again from the quickstart-reference bucket, as the changes in the v1.3 release have been published and the content there contains a few additional bug fixes.

**Comment by jaymccon** [comment]
This upstream issue looks relevant https://github.com/kubernetes/kubernetes/issues/59326

**Comment by jaymccon** [comment]
@philipho11 I was unable to replicate the NoVolumeZoneConflict issue with the persistent mongo from the catalog. Can you please provide the output of:

* `oc describe` for the mongo pod  and pv/pvc (if any)
* `oc get nodes --show-labels`

**Comment by philipho11** [comment]
@jaymccon I was using only one application node instead of three (3 master and 3 etcd though). k8s sig-aws points out that "your volumes aren't in the same AZ as your pods". And it is true. 

It seems that I cannot replicate after changing back to 3 app nodes. I can further test later on 1 app node situation.

**Comment by dudash** [comment]
So, I re-ran this today with the latest quickstart.  I'm still getting a stack create failed on the AnsibleConfigServer.  But the cluster seems to be up and running fine.   I can get to the web console, create pods, route to them, etc...  

But I pulled the logs anyway.  The cloud-init log looked normal.  The ansible.log ends with:

```
2018-03-28 22:00:18,341 p=23269 u=root |  INSTALLER STATUS ***************************************************************
2018-03-28 22:00:18,342 p=23269 u=root |  Initialization             : Complete
2018-03-28 22:00:18,342 p=23269 u=root |  Health Check               : Complete
2018-03-28 22:00:18,342 p=23269 u=root |  etcd Install               : Complete
2018-03-28 22:00:18,342 p=23269 u=root |  Master Install             : Complete
2018-03-28 22:00:18,342 p=23269 u=root |  Master Additional Install  : Complete
2018-03-28 22:00:18,342 p=23269 u=root |  Node Install               : Complete
2018-03-28 22:00:18,342 p=23269 u=root |  Hosted Install             : Complete
2018-03-28 22:00:18,343 p=23269 u=root |  Metrics Install            : Complete
2018-03-28 22:00:18,343 p=23269 u=root |  Service Catalog Install    : In Progress
2018-03-28 22:00:18,343 p=23269 u=root |  	This phase can be restarted by running: playbooks/byo/openshift-cluster/service-catalog.yml
2018-03-28 22:00:18,343 p=23269 u=root |  Failure summary:

  1. Hosts:    ip-10-0-85-242.us-east-2.compute.internal
     Play:     Configure nodes
     Task:     restart node
     Message:  Unable to restart service atomic-openshift-node: Job for atomic-openshift-node.service failed because the control process exited with error code. See "systemctl status atomic-openshift-node.service" and "journalctl -xe" for details.

  2. Hosts:    ip-10-0-88-243.us-east-2.compute.internal
     Play:     Service Catalog
     Task:     wait for api server to be ready
     Message:  non-zero return code
```

**[SNIP A BUNCH OF SUCCESS MESSAGES]**

```
2018-03-28 22:00:52,943 p=8462 u=root |  ip-10-0-26-28.us-east-2.compute.internal | FAILED | rc=1 >>
Job for atomic-openshift-node.service failed because the control process exited with error code. See "systemctl status atomic-openshift-node.service" and "journalctl -xe" for details.non-zero return code

2018-03-28 22:00:53,809 p=8462 u=root |  ip-10-0-43-139.us-east-2.compute.internal | FAILED | rc=1 >>
Job for atomic-openshift-node.service failed because the control process exited with error code. See "systemctl status atomic-openshift-node.service" and "journalctl -xe" for details.non-zero return code
```

**[SNIP A BUNCH OF SUCCESS MESSAGES]**

So it looks like maybe an error with the service catalog or maybe with a master (10.0.26.28) and an app node (10.0.43.139).  When I check `systemctl status` both of those nodes are active (running).  And the `journalctl -xe` the only thing that looks weird is this:
```
Mar 29 01:01:58 ip-10-0-26-28.us-east-2.compute.internal sshd[58622]: Did not receive identification string from 10.0.12.68 port 14051
Mar 29 01:01:59 ip-10-0-26-28.us-east-2.compute.internal atomic-openshift-node[25330]: I0329 01:01:59.893508   25330 aws.go:988] Could not determine public DNS from AWS metadata.
```

**Comment by dudash** [comment]
A little more info - after digging into `journalctl -u atomic-openshift-node` I'm seeing an error on both of those nodes that FAILED that looks like:
```
DN node startup failed: failed to validate network configuration: cannot fetch "default" cluster network: Get https://internal-Red-Hat-O-OpenShif-1SS5OO6ILVSK7-1207633200.us-east-2.elb.amazonaws.com:443/apis/network.openshift.io/v1/clusternetworks/default: net/http: TLS handshake timeout
```

```
Mar 28 22:00:53 ip-10-0-43-139.us-east-2.compute.internal systemd[1]: atomic-openshift-node.service: main process exited, code=exited, status=255/n/a
Mar 28 22:00:53 ip-10-0-43-139.us-east-2.compute.internal systemd[1]: Failed to start OpenShift Node.
Mar 28 22:00:53 ip-10-0-43-139.us-east-2.compute.internal systemd[1]: Unit atomic-openshift-node.service entered failed state.
Mar 28 22:00:53 ip-10-0-43-139.us-east-2.compute.internal systemd[1]: atomic-openshift-node.service failed.
Mar 28 22:00:58 ip-10-0-43-139.us-east-2.compute.internal systemd[1]: atomic-openshift-node.service holdoff time over, scheduling restart.
Mar 28 22:00:58 ip-10-0-43-139.us-east-2.compute.internal systemd[1]: Starting OpenShift Node...
```

**Comment by jwj019** [comment]
I've started seeing errors similar to this as of April 10th.  I've tried in us-east Ohio and Northern Virginia and us-west Oregon.  This occurs when using both version 3.7 and 3.9. Here are the parameters from my last attempt:

Key | Value
-- | -- 
AvailabilityZones | us-east-2a,us-east-2b,us-east-2c 
AWSServiceBroker | Disabled 
ContainerAccessCIDR | 0.0.0.0/0 
DomainName | REMOVED 
EtcdInstanceType | m4.xlarge 
ExistingAWSServiceBrokerRole |   
HawkularMetrics | Enabled 
HostedZoneID | REMOVED
KeyPairName | openshift-04 
MasterInstanceType | m4.xlarge 
NodesInstanceType | m4.xlarge 
NumberOfEtcd | 3 
NumberOfMaster | 3 
NumberOfNodes | 3 
OpenShiftAdminPassword | **** 
OpenshiftContainerPlatformVersion | 3.7 
OutputBucketName |   
PrivateSubnet1CIDR | 10.0.0.0/19 
PrivateSubnet2CIDR | 10.0.32.0/19 
PrivateSubnet3CIDR | 10.0.64.0/19 
PublicSubnet1CIDR | 10.0.128.0/20 
PublicSubnet2CIDR | 10.0.144.0/20 
PublicSubnet3CIDR | 10.0.160.0/20 
QSS3BucketName | aws-quickstart 
QSS3KeyPrefix | quickstart-redhat-openshift/ 
RedhatSubscriptionPassword | REMOVED
RedhatSubscriptionPoolID | REMOVED
RedhatSubscriptionUserName | REMOVED
RemoteAccessCIDR | REMOVED
SubDomainPrefix | openshift2 
VPCCIDR | 10.0.0.0/16

**Comment by jaymccon** [comment]
@dudash @jwj019 I beleive these issues have been resolved in the current master branch. 
Can you please re-test using the latest version in the [quickstart S3 bucket](https://s3.amazonaws.com/quickstart-reference/redhat/openshift/latest/templates/openshift-master.template)  or by cloning and publishing the current master branch to your own bucket.

**Comment by jwj019** [comment]
I'm getting a different failure on the AnsibleConfigServer now:


Apr 12 17:02:23 localhost cloud-init: + aws s3 cp s3://aws-quickstart/quickstart-redhat-openshift/scripts/openshift_config_ose.yml /root/openshift_config.yml
Apr 12 17:02:23 localhost cloud-init: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
Apr 12 17:02:23 localhost cloud-init: + qs_err ' Openshift installation failed, see logs for details '
Apr 12 17:02:23 localhost cloud-init: + touch /var/tmp/stack_failed
Apr 12 17:02:23 localhost cloud-init: + echo '[FAILED] @  Openshift installation failed, see logs for details '
Apr 12 17:02:23 localhost cloud-init: + echo '[FAILED] @  Openshift installation failed, see logs for details '
Apr 12 17:02:23 localhost cloud-init: [FAILED] @  Openshift installation failed, see logs for details
Apr 12 17:02:23 localhost cloud-init: ++ qs_status
Apr 12 17:02:23 localhost cloud-init: ++ '[' -f /var/tmp/stack_failed ']'
Apr 12 17:02:23 localhost cloud-init: ++ printf 1
Apr 12 17:02:23 localhost cloud-init: ++ return 1
Apr 12 17:02:23 localhost cloud-init: + cfn-signal -e 1 --stack Red-Hat-OpenShift18-OpenShiftStack-8SKUR2PXV64V --resource AnsibleConfigServer --region us-east-1

**Comment by dudash** [comment]
Trying again in Ohio region - I'm getting same error as @jwj019 .  It looks like that .yml file isn't in the s3 bucket or has bad permissions.

https://aws-quickstart.s3.amazonaws.com/quickstart-redhat-openshift/scripts/openshift_config_ose.yml

Referenced by:
https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/master/scripts/ansibleconfigserver_bootstrap.sh#L31

**Comment by jaymccon** [comment]
@dudash @jwj019 my apologies for the hassle, looks like some incomplete work made it through our CI and into the quickstart bucket, it has been rectified and our tests are showing successful builds now. If possible can you re-test and let us know if the issue seems resolved.

**Comment by dudash** [comment]
Stack creation success!  Thanks!

FYI, I do still see these warnings.  Some they might have been unrelated:
```atomic-openshift-node[26922]: I0412 22:28:34.025483   26922 aws.go:1017] Could not determine public DNS from AWS metadata.```

This issue is resolved for me.

**Comment by agamzn** [comment]
Those are unrelated from our perspective as well. Resolving this out.
